services:
  dbt:
    build: .
    volumes:
      - ./dbt_project:/usr/app/dbt_project
    # Load variables from the .env file
    env_file:
      - ./.env
    # Explicitly list the environment variables to be passed to the container
    environment:
      - DATABRICKS_HOST=${DATABRICKS_HOST}
      - DATABRICKS_HTTP_PATH=${DATABRICKS_HTTP_PATH}
      - DATABRICKS_TOKEN=${DATABRICKS_TOKEN}
    command: ["/bin/bash"]