name: Build & Push Docker Image to ACR

on:
  push:
    branches: [ "main", "feature/*" ]
    
  workflow_dispatch:

env:
  IMAGE_NAME: dbt-transform

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: docker/setup-buildx-action@v3

      - name: ACR Login
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build & Push
        run: |
          REGISTRY=${{ secrets.ACR_NAME }}.azurecr.io
          IMAGE=$REGISTRY/${{ env.IMAGE_NAME }}
          TAG=${{ github.sha }}

          docker buildx build \
            --push \
            -t $IMAGE:$TAG \
            -t $IMAGE:latest \
            .
